model_list:
  - model_name: mimo-v2.5
    litellm_params: {model: openai/mimo-v2.5, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}
  - model_name: mimo-v2.5-pro-ultraspeed
    litellm_params: {model: openai/mimo-v2.5-pro-ultraspeed, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}

  - model_name: mistral-medium-3-5
    litellm_params: {model: openai/mistral-medium-3-5, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}
  - model_name: tencent-hy3
    litellm_params: {model: openai/tencent-hy3, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}
  - model_name: mimo-v2.5-pro
    litellm_params: {model: openai/mimo-v2.5-pro, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}
  - model_name: gpt-5.6-luna
    litellm_params: {model: openai/gpt-5.6-luna, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}
  - model_name: kimi-k2.7-code-free
    litellm_params: {model: openai/kimi-k2.7-code-free, api_base: https://router.bynara.id/v1, api_key: os.environ/BYNARA_API_KEY_2}

litellm_settings:
  drop_params: true
  request_timeout: 90
