import { dict } from '@/lib/i18n'

const FA = {
  loadError: 'خطا در دریافت اطلاعات سرور',
  removeSkillError: 'خطا در حذف اسکیل',
  removeSkillSuccess: 'درخواست حذف اسکیل ثبت شد',
  updateSkillError: 'خطا در بروزرسانی اسکیل',
  networkError: 'خطا در ارتباط با سرور',
  signIn: 'وارد شوید',
  loginToAccount: 'ورود به حساب',
  back: 'بازگشت',
  serverNumber: (id: string) => `سرور #${id}`,
  ip: 'آی‌پی',
  status: 'وضعیت',
  sync: 'همگام‌سازی',
  lastAgentHeartbeat: 'آخرین اتصال ایجنت',
  monthlyCost: 'هزینه ماهانه',
  paidThrough: 'پرداخت‌شده تا',
  inSync: 'همگام',
  pendingSync: (applied: string, desired: string) => `در انتظار (${applied}/${desired})`,
  neverConnected: 'هنوز متصل نشده',
  installedSkills: 'اسکیل‌های نصب‌شده',
  addSkill: 'افزودن اسکیل',
  noSkillsInstalled: 'هنوز اسکیلی روی این سرور نصب نشده است.',
  disable: 'غیرفعال کردن',
  enable: 'فعال کردن',
  add: 'افزودن',
  addSkillModalTitle: 'افزودن اسکیل',
  addSkillError: 'خطا در افزودن اسکیل',
  addSkillSuccess: 'اسکیل به سرور اضافه شد',
  statusLabel: {
    active: 'فعال',
    suspended: 'متوقف‌شده',
    provisioning: 'در حال راه‌اندازی',
    terminated: 'خاتمه‌یافته',
  },
  skillState: {
    pending: 'در حال اعمال',
    installed: 'نصب‌شده',
    failed: 'خطا',
    removing: 'در حال حذف',
  },
}

const EN: typeof FA = {
  loadError: 'Failed to load server details',
  removeSkillError: 'Failed to remove skill',
  removeSkillSuccess: 'Skill removal request submitted',
  updateSkillError: 'Failed to update skill',
  networkError: 'Connection error',
  signIn: 'Sign in',
  loginToAccount: 'Sign in to your account',
  back: 'Back',
  serverNumber: (id) => `Server #${id}`,
  ip: 'IP address',
  status: 'Status',
  sync: 'Sync',
  lastAgentHeartbeat: 'Last agent heartbeat',
  monthlyCost: 'Monthly cost',
  paidThrough: 'Paid through',
  inSync: 'In sync',
  pendingSync: (applied, desired) => `Pending (${applied}/${desired})`,
  neverConnected: 'Not connected yet',
  installedSkills: 'Installed skills',
  addSkill: 'Add skill',
  noSkillsInstalled: 'No skills installed on this server yet.',
  disable: 'Disable',
  enable: 'Enable',
  add: 'Add',
  addSkillModalTitle: 'Add skill',
  addSkillError: 'Failed to add skill',
  addSkillSuccess: 'Skill added to server',
  statusLabel: {
    active: 'Active',
    suspended: 'Suspended',
    provisioning: 'Provisioning',
    terminated: 'Terminated',
  },
  skillState: {
    pending: 'Applying',
    installed: 'Installed',
    failed: 'Failed',
    removing: 'Removing',
  },
}

export const hermesServerDetailStrings = dict(FA, EN)
