import { dict } from '@/lib/i18n'

const FA = {
  title: 'کلیدهای API',
  subtitle: 'مدیریت کلیدهای دسترسی به API',
  forbiddenMessage: 'درخواست شما رد شد (خطای امنیتی). لطفاً صفحه را تازه‌سازی کرده و دوباره تلاش کنید.',
  genericError: 'خطا',
  connectionError: 'خطا در ارتباط',
  revoked: 'کلید غیرفعال شد',
  revokeError: 'خطا',
  generateTitle: 'ساخت کلید جدید',
  namePlaceholder: 'نام کلید (مثلاً Production)',
  create: 'ساخت کلید',
  yourKeys: 'کلیدهای شما',
  emptyTitle: 'هنوز کلیدی نساخته‌اید',
  emptyDesc: 'از فرم بالا اولین کلید API خود را بسازید',
  active: 'فعال',
  inactive: 'غیرفعال',
  createdAt: (date: string) => `ساخت: ${date}`,
  lastUsed: (date: string) => `آخرین استفاده: ${date}`,
  requestsCount: (n: string) => `${n} درخواست`,
  rotateTitle: 'چرخاندن کلید (ساخت رمز جدید)',
  revokeTitle: 'غیرفعال کردن',
  rotateConfirm: 'با چرخاندن این کلید، کلید فعلی بلافاصله از کار می‌افتد و باید کلید جدید را در همه جا جایگزین کنید. ادامه می‌دهید؟',
  howToUse: 'نحوه استفاده',
  step1: 'احراز هویت',
  step2: 'ارسال درخواست چت',
  step3: 'لیست مدل‌ها',
}

const EN: typeof FA = {
  title: 'API keys',
  subtitle: 'Manage your API access keys',
  forbiddenMessage: 'Your request was rejected (security error). Please refresh the page and try again.',
  genericError: 'Error',
  connectionError: 'Connection error',
  revoked: 'Key disabled',
  revokeError: 'Error',
  generateTitle: 'Create a new key',
  namePlaceholder: 'Key name (e.g. Production)',
  create: 'Create key',
  yourKeys: 'Your keys',
  emptyTitle: 'You haven’t created a key yet',
  emptyDesc: 'Create your first API key from the form above',
  active: 'Active',
  inactive: 'Inactive',
  createdAt: (date) => `Created: ${date}`,
  lastUsed: (date) => `Last used: ${date}`,
  requestsCount: (n) => `${n} requests`,
  rotateTitle: 'Rotate key (generate a new secret)',
  revokeTitle: 'Disable',
  rotateConfirm: 'Rotating this key immediately disables the current one — you’ll need to replace it everywhere it’s used. Continue?',
  howToUse: 'How to use',
  step1: 'Authenticate',
  step2: 'Send a chat request',
  step3: 'List models',
}

export const apiKeysPageStrings = dict(FA, EN)
