import { dict } from '@/lib/i18n'

const FA = {
  requiredFieldsToast: 'لطفاً فیلدهای ضروری را پر کنید',
  createdToast: 'مهارت با موفقیت ایجاد شد',
  createErrorToast: 'خطا در ایجاد مهارت',
  serverErrorToast: 'خطا در ارتباط با سرور',
  modalTitle: 'ایجاد مهارت جدید',
  closeAria: 'بستن',
  titleLabel: 'عنوان *',
  titlePlaceholder: 'عنوان مهارت را وارد کنید',
  descriptionLabel: 'توضیحات',
  descriptionPlaceholder: 'توضیحات مهارت را وارد کنید',
  categoryLabel: 'دسته‌بندی',
  promptLabel: 'الگوی پرامپت *',
  promptPlaceholder: 'الگوی پرامپت را وارد کنید. از {{variable_name}} برای متغیرها استفاده کنید.',
  variablesLabel: 'متغیرها',
  addAction: 'افزودن',
  variableNamePlaceholder: 'نام متغیر',
  variableDescPlaceholder: 'توضیحات',
  removeVariableAria: 'حذف متغیر',
  defaultModelLabel: 'مدل پیش‌فرض',
  defaultModelPlaceholder: 'نام مدل (اختیاری)',
  tagsLabel: 'برچسب‌ها (با کاما جدا کنید)',
  tagsPlaceholder: 'برچسب۱, برچسب۲, ...',
  publicAria: (isPublic: boolean): string => (isPublic ? 'عمومی' : 'خصوصی'),
  publicHint: (isPublic: boolean): string =>
    isPublic ? 'عمومی — برای همه قابل مشاهده' : 'خصوصی — فقط برای شما',
  savingText: 'در حال ذخیره...',
  saveAction: 'ذخیره',
}

const EN: typeof FA = {
  requiredFieldsToast: 'Please fill in the required fields',
  createdToast: 'Skill created successfully',
  createErrorToast: 'Failed to create skill',
  serverErrorToast: 'Server connection error',
  modalTitle: 'Create new skill',
  closeAria: 'Close',
  titleLabel: 'Title *',
  titlePlaceholder: 'Enter the skill title',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'Enter the skill description',
  categoryLabel: 'Category',
  promptLabel: 'Prompt template *',
  promptPlaceholder: 'Enter the prompt template. Use {{variable_name}} for variables.',
  variablesLabel: 'Variables',
  addAction: 'Add',
  variableNamePlaceholder: 'Variable name',
  variableDescPlaceholder: 'Description',
  removeVariableAria: 'Remove variable',
  defaultModelLabel: 'Default model',
  defaultModelPlaceholder: 'Model name (optional)',
  tagsLabel: 'Tags (comma-separated)',
  tagsPlaceholder: 'tag1, tag2, ...',
  publicAria: (isPublic) => (isPublic ? 'Public' : 'Private'),
  publicHint: (isPublic) => (isPublic ? 'Public — visible to everyone' : 'Private — visible to you only'),
  savingText: 'Saving...',
  saveAction: 'Save',
}

export const createSkillModalStrings = dict(FA, EN)
