import { dict } from '@/lib/i18n'

const FA = {
  title: 'مقایسه مدل‌ها',
  subtitle: 'دو مدل را انتخاب کنید، یک prompt بنویسید و پاسخ‌ها را کنار هم مقایسه کنید',
  modelA: 'مدل A',
  modelB: 'مدل B',
  vs: 'VS',
  promptPlaceholder: 'prompt خود را بنویسید... (Ctrl+Enter برای ارسال)',
  comparing: 'در حال مقایسه...',
  compare: 'مقایسه',
  noModelsTitle: 'مدلی برای مقایسه نیست',
  noModelsDesc: 'فهرست مدل‌ها خالی است؛ پس از بارگذاری مدل‌ها می‌توانید آنها را مقایسه کنید.',
  noModelSelected: 'مدل انتخاب نشده',
  faster: 'سریع‌تر',
  cheaper: 'ارزان‌تر',
  time: 'زمان',
  tokensInput: 'توکن ورودی',
  tokensOutput: 'توکن خروجی',
  cost: 'هزینه',
  receiving: 'در حال دریافت پاسخ...',
  placeholder: 'پاسخ مدل در اینجا نمایش داده می‌شود',
  fetchModelsError: 'خطا در دریافت فهرست مدل‌ها',
  insufficientBalance: 'موجودی کیف پول کافی نیست. لطفاً حساب خود را شارژ کنید.',
  connectionError: 'خطا در ارتباط',
  serverError: (status: string) => `خطای سرور: ${status}`,
  webSearch: 'جستجوی وب',
  // ── History + continue (session mode) ──────────────────────────────────
  continuePlaceholder: 'ادامه گفتگو را بنویسید... (Ctrl+Enter برای ارسال به هر دو)',
  sendToA: 'فقط ارسال به A',
  sendToB: 'فقط ارسال به B',
  openSidebar: 'نمایش تاریخچه',
  closeSidebar: 'پنهان‌کردن تاریخچه',
  historyAriaLabel: 'تاریخچه مقایسه‌ها',
  loadSessionFailed: 'خطا در بارگذاری تاریخچه مقایسه',
  deleteSessionFailed: 'خطا در حذف مقایسه',
}

const EN: typeof FA = {
  title: 'Compare models',
  subtitle: 'Pick two models, write a prompt, and compare the answers side by side',
  modelA: 'Model A',
  modelB: 'Model B',
  vs: 'VS',
  promptPlaceholder: 'Write your prompt... (Ctrl+Enter to send)',
  comparing: 'Comparing...',
  compare: 'Compare',
  noModelsTitle: 'No models to compare',
  noModelsDesc: 'The model list is empty; once models load you’ll be able to compare them.',
  noModelSelected: 'No model selected',
  faster: 'Faster',
  cheaper: 'Cheaper',
  time: 'Time',
  tokensInput: 'Input tokens',
  tokensOutput: 'Output tokens',
  cost: 'Cost',
  receiving: 'Receiving response...',
  placeholder: 'The model’s response will appear here',
  fetchModelsError: 'Error loading the model list',
  insufficientBalance: 'Your wallet balance is insufficient. Please top up your account.',
  connectionError: 'Connection error',
  serverError: (status) => `Server error: ${status}`,
  webSearch: 'Web search',
  // ── History + continue (session mode) ──────────────────────────────────
  continuePlaceholder: 'Continue the conversation... (Ctrl+Enter to send to both)',
  sendToA: 'Send to A only',
  sendToB: 'Send to B only',
  openSidebar: 'Show history',
  closeSidebar: 'Hide history',
  historyAriaLabel: 'Compare history',
  loadSessionFailed: 'Failed to load the compare history',
  deleteSessionFailed: 'Failed to delete the comparison',
}

export const comparePageStrings = dict(FA, EN)
