import { dict } from '@/lib/i18n'

const FA = {
  requiredNameToast: 'نام دستیار الزامی است',
  requiredPromptToast: 'پرامپت سیستم الزامی است',
  createdToast: 'دستیار با موفقیت ساخته شد',
  createErrorFallback: 'خطا در ساخت دستیار',
  serverErrorToast: 'خطا در ارتباط با سرور',
  backAction: 'بازگشت به دستیارها',
  pageTitle: 'ساخت دستیار جدید',
  pageSubtitle: 'یک دستیار هوشمند با پرامپت سیستم سفارشی بسازید',
  nameLabel: 'نام دستیار',
  namePlaceholder: 'مثال: دستیار برنامه‌نویسی',
  descriptionLabel: 'توضیحات',
  descriptionPlaceholder: 'توضیح کوتاه درباره دستیار',
  systemPromptLabel: 'پرامپت سیستم',
  systemPromptPlaceholder: 'تو یک دستیار متخصص در... هستی. وظیفه تو...',
  systemPromptHint: 'این پرامپت در ابتدای هر مکالمه به مدل ارسال می‌شود',
  defaultModelLabel: 'مدل پیش‌فرض',
  noDefaultModelOption: 'بدون مدل پیش‌فرض (استفاده از مدل انتخابی کاربر)',
  defaultModelHint: 'در صورت انتخاب، هنگام شروع گفتگو با این دستیار، این مدل استفاده می‌شود',
  publicLabel: 'عمومی',
  privateLabel: 'خصوصی',
  publicHintOn: 'همه کاربران می‌توانند از این دستیار استفاده کنند',
  publicHintOff: 'فقط شما به این دستیار دسترسی دارید',
  cancelAction: 'انصراف',
  creatingText: 'در حال ساخت...',
  createAction: 'ساخت دستیار',
}

const EN: typeof FA = {
  requiredNameToast: 'Assistant name is required',
  requiredPromptToast: 'System prompt is required',
  createdToast: 'Assistant created successfully',
  createErrorFallback: 'Failed to create assistant',
  serverErrorToast: 'Server connection error',
  backAction: 'Back to assistants',
  pageTitle: 'Create new assistant',
  pageSubtitle: 'Build a smart assistant with a custom system prompt',
  nameLabel: 'Assistant name',
  namePlaceholder: 'e.g. Coding assistant',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'A short description of the assistant',
  systemPromptLabel: 'System prompt',
  systemPromptPlaceholder: 'You are an assistant specialized in... Your task is...',
  systemPromptHint: 'This prompt is sent to the model at the start of every conversation',
  defaultModelLabel: 'Default model',
  noDefaultModelOption: "No default model (use the user's selected model)",
  defaultModelHint: 'If selected, this model is used when starting a conversation with this assistant',
  publicLabel: 'Public',
  privateLabel: 'Private',
  publicHintOn: 'All users can use this assistant',
  publicHintOff: 'Only you have access to this assistant',
  cancelAction: 'Cancel',
  creatingText: 'Creating...',
  createAction: 'Create assistant',
}

export const newAssistantPageStrings = dict(FA, EN)
