import { dict } from '@/lib/i18n'

const FA = {
  historyLoadError: 'خطا در دریافت سوابق تولید سند',
  genericGenerateError: 'خطا در تولید سند',
  unknownError: 'خطای ناشناخته',
  deleteFailed: 'حذف سند ناموفق بود',
  networkError: 'خطا در ارتباط با سرور',
  docTypes: {
    pptx: { label: 'PowerPoint', desc: 'ارائه حرفه‌ای با اسلایدهای زیبا' },
    docx: { label: 'Word', desc: 'سند متنی با ساختار حرفه‌ای' },
    mdx: { label: 'Markdown Slides', desc: 'اسلاید Markdown (Marp/reveal.js)' },
  },
  loginTitle: 'سندساز',
  loginBody: 'برای ساخت پاورپوینت، ورد یا اسلاید با هوش مصنوعی، ابتدا وارد حساب خود شوید.',
  loginCta: 'ورود / ثبت‌نام',
  pageTitle: 'تولید سند با هوش مصنوعی',
  pageSubtitle: 'ارائه PowerPoint، سند Word یا اسلاید Markdown با یک پرامپت بسازید',
  docTypeCardHeader: 'نوع سند',
  promptCardHeader: 'توضیحات سند',
  promptPlaceholder: 'توضیح دهید چه سندی می‌خواهید... مثال: یک ارائه ۱۰ اسلایدی درباره آینده AI',
  suggestions: [
    'یک ارائه درباره آینده هوش مصنوعی بساز',
    'گزارش تحلیلی بازار ارز دیجیتال',
    'مقاله درباره بهترین شیوه‌های توسعه نرم‌افزار',
    'ارائه معرفی استارتاپ Sanjabai',
    'سند نقشه راه محصول ۱۴۰۵',
  ],
  generating: 'در حال تولید سند...',
  generateButton: (label: string) => `ساخت ${label}`,
  slidesCount: (n: string) => `${n} اسلاید`,
  sectionsCount: (n: string) => `${n} بخش`,
  seconds: (n: string) => `${n} ثانیه`,
  download: 'دانلود فایل',
  historyHeader: 'سوابق تولید',
  noHistory: 'هنوز سندی تولید نشده',
}

const EN: typeof FA = {
  historyLoadError: 'Failed to load document history',
  genericGenerateError: 'Failed to generate document',
  unknownError: 'Unknown error',
  deleteFailed: 'Failed to delete document',
  networkError: 'Connection error',
  docTypes: {
    pptx: { label: 'PowerPoint', desc: 'A professional presentation with polished slides' },
    docx: { label: 'Word', desc: 'A text document with professional structure' },
    mdx: { label: 'Markdown Slides', desc: 'Markdown slides (Marp/reveal.js)' },
  },
  loginTitle: 'Document generator',
  loginBody: 'Sign in to your account to build a PowerPoint, Word document, or slide deck with AI.',
  loginCta: 'Sign in / Sign up',
  pageTitle: 'AI document generation',
  pageSubtitle: 'Build a PowerPoint presentation, Word document, or Markdown slide deck from one prompt',
  docTypeCardHeader: 'Document type',
  promptCardHeader: 'Document description',
  promptPlaceholder: 'Describe the document you want... e.g. a 10-slide presentation about the future of AI',
  suggestions: [
    'Build a presentation about the future of AI',
    'An analytical report on the crypto market',
    'An article on software development best practices',
    'A pitch deck for the startup Sanjabai',
    'A product roadmap document for 1405',
  ],
  generating: 'Generating document...',
  generateButton: (label) => `Generate ${label}`,
  slidesCount: (n) => `${n} slides`,
  sectionsCount: (n) => `${n} sections`,
  seconds: (n) => `${n}s`,
  download: 'Download file',
  historyHeader: 'Generation history',
  noHistory: 'No document generated yet',
}

export const documentsPageStrings = dict(FA, EN)
