server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /static/ {
        alias /usr/share/nginx/html/static/;
        expires 1d;
    }

    location /api/admin/ {
        proxy_pass http://sanjhubai_api:8000/api/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
