import { dict } from '@/lib/i18n'

const FA = {
  paymentFailed: 'پرداخت سفارش ناموفق بود یا لغو شد. مبلغی از حساب شما کسر نشده است؛ می‌توانید دوباره تلاش کنید.',
  paymentError: 'خطایی در پردازش پرداخت رخ داد. اگر مبلغی کسر شده باشد، به‌زودی بازمی‌گردد.',
  loadError: 'خطا در دریافت اطلاعات سرویس',
  maxSkillsReached: (n: string) => `این پلن حداکثر ${n} اسکیل پشتیبانی می‌کند`,
  submitError: 'خطا در ثبت سفارش',
  networkError: 'خطا در ارتباط با سرور',
  signIn: 'وارد شوید',
  loginPrompt: 'برای سفارش سرور هرمس ابتدا وارد حساب کاربری خود شوید.',
  loginToAccount: 'ورود به حساب',
  close: 'بستن',
  pageTitle: 'سفارش سرور هرمس',
  step1Title: (n: string) => `${n}. انتخاب پلن سرور`,
  step2Title: (n: string) => `${n}. انتخاب اسکیل‌ها`,
  maxSkillsHint: (n: string) => `(حداکثر ${n})`,
  step3Title: (n: string) => `${n}. فاکتور`,
  perMonth: '/ماه',
  setupCost: 'هزینه راه‌اندازی',
  firstMonth: 'ماه اول',
  totalPayable: 'مجموع پرداختی',
  payAndSubmit: 'پرداخت و ثبت سفارش',
  maxOptionsReached: (n: string) => `حداکثر ${n} مورد قابل انتخاب است`,
  commaSeparated: '(با ، جدا کنید)',
  schedule: 'زمان‌بندی (cron)',
}

const EN: typeof FA = {
  paymentFailed: 'The order payment failed or was cancelled. No amount was deducted from your account; you can try again.',
  paymentError: 'An error occurred while processing payment. If an amount was deducted, it will be refunded shortly.',
  loadError: 'Failed to load service information',
  maxSkillsReached: (n) => `This plan supports at most ${n} skills`,
  submitError: 'Failed to place order',
  networkError: 'Connection error',
  signIn: 'Sign in',
  loginPrompt: 'Sign in to your account first to order a Hermes server.',
  loginToAccount: 'Sign in to your account',
  close: 'Close',
  pageTitle: 'Order a Hermes server',
  step1Title: (n) => `${n}. Choose a server plan`,
  step2Title: (n) => `${n}. Choose skills`,
  maxSkillsHint: (n) => `(max ${n})`,
  step3Title: (n) => `${n}. Invoice`,
  perMonth: '/mo',
  setupCost: 'Setup cost',
  firstMonth: 'First month',
  totalPayable: 'Total payable',
  payAndSubmit: 'Pay and place order',
  maxOptionsReached: (n) => `At most ${n} items can be selected`,
  commaSeparated: '(comma separated)',
  schedule: 'Schedule (cron)',
}

export const hermesOrderStrings = dict(FA, EN)
