import { dict } from '@/lib/i18n'

const FA = {
  notFoundTitle: 'دستیار یافت نشد',
  notFoundDesc: 'دستیار مورد نظر وجود ندارد یا حذف شده است.',
  backToAssistants: 'بازگشت به دستیارها',
  editTitle: 'ویرایش دستیار',
  createdOn: (date: string) => `ساخته شده در ${date}`,
  startChat: 'شروع گفتگو',
  nameLabel: 'نام دستیار',
  namePlaceholder: 'مثال: دستیار برنامه‌نویسی',
  descriptionLabel: 'توضیحات',
  descriptionPlaceholder: 'توضیح کوتاه درباره دستیار',
  systemPromptLabel: 'پرامپت سیستم',
  systemPromptPlaceholder: 'تو یک دستیار متخصص در... هستی. وظیفه تو...',
  systemPromptHint: 'این پرامپت در ابتدای هر مکالمه به مدل ارسال می‌شود',
  defaultModelLabel: 'مدل پیش‌فرض',
  noDefaultModelOption: 'بدون مدل پیش‌فرض (استفاده از مدل انتخابی کاربر)',
  publicLabel: 'عمومی',
  privateLabel: 'خصوصی',
  publicHintOn: 'همه کاربران می‌توانند از این دستیار استفاده کنند',
  publicHintOff: 'فقط شما به این دستیار دسترسی دارید',
  deletingText: 'در حال حذف...',
  confirmDeleteAction: 'تأیید حذف',
  deleteAction: 'حذف دستیار',
  savingText: 'در حال ذخیره...',
  saveChangesAction: 'ذخیره تغییرات',
  requiredNameToast: 'نام دستیار الزامی است',
  requiredPromptToast: 'پرامپت سیستم الزامی است',
  updatedToast: 'دستیار با موفقیت بروزرسانی شد',
  updateErrorFallback: 'خطا در بروزرسانی دستیار',
  serverErrorToast: 'خطا در ارتباط با سرور',
  deleteSuccessToast: 'دستیار حذف شد',
  deleteErrorToast: 'خطا در حذف دستیار',
}

const EN: typeof FA = {
  notFoundTitle: 'Assistant not found',
  notFoundDesc: 'This assistant does not exist or has been removed.',
  backToAssistants: 'Back to assistants',
  editTitle: 'Edit assistant',
  createdOn: (date) => `Created on ${date}`,
  startChat: 'Start chat',
  nameLabel: 'Assistant name',
  namePlaceholder: 'e.g. Coding assistant',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'A short description of the assistant',
  systemPromptLabel: 'System prompt',
  systemPromptPlaceholder: 'You are an assistant specialized in... Your task is...',
  systemPromptHint: 'This prompt is sent to the model at the start of every conversation',
  defaultModelLabel: 'Default model',
  noDefaultModelOption: "No default model (use the user's selected model)",
  publicLabel: 'Public',
  privateLabel: 'Private',
  publicHintOn: 'All users can use this assistant',
  publicHintOff: 'Only you have access to this assistant',
  deletingText: 'Deleting...',
  confirmDeleteAction: 'Confirm delete',
  deleteAction: 'Delete assistant',
  savingText: 'Saving...',
  saveChangesAction: 'Save changes',
  requiredNameToast: 'Assistant name is required',
  requiredPromptToast: 'System prompt is required',
  updatedToast: 'Assistant updated successfully',
  updateErrorFallback: 'Failed to update assistant',
  serverErrorToast: 'Server connection error',
  deleteSuccessToast: 'Assistant deleted',
  deleteErrorToast: 'Failed to delete assistant',
}

export const assistantDetailPageStrings = dict(FA, EN)
