import { dict } from '@/lib/i18n'

const FA = {
  notFoundTitle: 'اسکیل یافت نشد',
  notFoundDesc: 'اسکیل مورد نظر وجود ندارد یا حذف شده است.',
  backToMarketplace: 'بازگشت به مارکتپلیس',
  featuredBadge: 'ویژه',
  reviewsCount: (n: string) => `(${n} نظر)`,
  usageCount: (n: string) => `${n} استفاده`,
  shareAction: 'اشتراک‌گذاری',
  notAuthText: 'برای استفاده از این اسکیل، ابتدا وارد حساب کاربری خود شوید.',
  signInAction: 'ورود به حساب',
  runSkillHeading: 'اجرای اسکیل',
  modelLabel: 'مدل',
  modelPlaceholder: 'نام مدل',
  variablesLabel: 'متغیرها',
  runningText: 'در حال اجرا...',
  runAction: 'اجرا',
  outputLabel: 'خروجی',
  copyAction: 'کپی',
  copiedToast: 'کپی شد',
  modelResultLabel: (model: string) => `مدل: ${model}`,
  ratingHeading: 'امتیازدهی',
  yourRating: 'امتیاز شما:',
  starAria: (n: number) => `${n} ستاره`,
  promptTemplateHeading: 'الگوی پرامپت',
  toastUseError: 'خطا در اجرای اسکیل',
  toastServerError: 'خطا در ارتباط با سرور',
  toastRateSuccess: 'امتیاز شما ثبت شد',
  toastRateError: 'خطا در ثبت امتیاز',
  toastLinkCopied: 'لینک کپی شد',
  toastSignInFirst: 'ابتدا وارد شوید',
}

const EN: typeof FA = {
  notFoundTitle: 'Skill not found',
  notFoundDesc: 'This skill does not exist or has been removed.',
  backToMarketplace: 'Back to marketplace',
  featuredBadge: 'Featured',
  reviewsCount: (n) => `(${n} reviews)`,
  usageCount: (n) => `${n} uses`,
  shareAction: 'Share',
  notAuthText: 'Sign in to your account to use this skill.',
  signInAction: 'Sign in',
  runSkillHeading: 'Run skill',
  modelLabel: 'Model',
  modelPlaceholder: 'Model name',
  variablesLabel: 'Variables',
  runningText: 'Running...',
  runAction: 'Run',
  outputLabel: 'Output',
  copyAction: 'Copy',
  copiedToast: 'Copied',
  modelResultLabel: (model) => `Model: ${model}`,
  ratingHeading: 'Rating',
  yourRating: 'Your rating:',
  starAria: (n) => `${n} stars`,
  promptTemplateHeading: 'Prompt template',
  toastUseError: 'Failed to run skill',
  toastServerError: 'Server connection error',
  toastRateSuccess: 'Your rating was saved',
  toastRateError: 'Failed to save rating',
  toastLinkCopied: 'Link copied',
  toastSignInFirst: 'Please sign in first',
}

export const skillDetailPageStrings = dict(FA, EN)
