import { dict } from '@/lib/adminI18n'

const FA = {
  title: 'امکانات و ویژگی‌ها',
  subtitle: (n: string) => `${n} ویژگی ثبت شده`,
  loadError: 'خطا در دریافت ویژگی‌ها',
  noneRegistered: 'ویژگی‌ای ثبت نشده',
  noDescription: 'بدون توضیح',
  active: 'فعال',
  disabled: 'غیرفعال',
  editTitle: 'ویرایش ویژگی',
  addTitle: 'افزودن ویژگی جدید',
  titleField: 'عنوان',
  titlePlaceholder: 'چت هوشمند',
  iconField: 'آیکون',
  descriptionField: 'توضیحات',
  orderField: 'ترتیب نمایش',
  statusField: 'وضعیت',
  update: 'بروزرسانی',
  add: 'افزودن',
  cancel: 'انصراف',
  saveEditSuccess: 'ویژگی ویرایش شد',
  saveAddSuccess: 'ویژگی اضافه شد',
  saveError: 'خطا در ذخیره ویژگی',
  deleteSuccess: 'ویژگی حذف شد',
  deleteError: 'خطا در حذف ویژگی',
}

const EN: typeof FA = {
  title: 'Features',
  subtitle: (n) => `${n} feature${n === '1' ? '' : 's'} registered`,
  loadError: 'Failed to load features',
  noneRegistered: 'No features registered',
  noDescription: 'No description',
  active: 'Active',
  disabled: 'Disabled',
  editTitle: 'Edit feature',
  addTitle: 'Add new feature',
  titleField: 'Title',
  titlePlaceholder: 'Smart chat',
  iconField: 'Icon',
  descriptionField: 'Description',
  orderField: 'Display order',
  statusField: 'Status',
  update: 'Update',
  add: 'Add',
  cancel: 'Cancel',
  saveEditSuccess: 'Feature updated',
  saveAddSuccess: 'Feature added',
  saveError: 'Failed to save feature',
  deleteSuccess: 'Feature deleted',
  deleteError: 'Failed to delete feature',
}

export const featuresStrings = dict(FA, EN)
