import { dict } from '@/lib/adminI18n'

const FA = {
  title: 'حساب رایگان',
  subtitle: 'سقف پیام و مدل‌های مجاز برای کاربر بدون شارژ',
  fullSubtitle: 'سقف پیام ساعتی و مادام‌العمر و سقف قیمت مدل‌های مجاز برای کاربر بدون شارژ و بدون بسته — بدون نیاز به ری‌استارت',
  loadError: 'خطا در دریافت تنظیمات حساب رایگان',
  serverError: (status: string) => `خطای سرور (${status})`,
  loadFailedTitle: 'دریافت تنظیمات ناموفق بود',
  retry: 'تلاش دوباره',
  loading: 'در حال بارگذاری…',
  noData: 'اطلاعاتی یافت نشد',
  hourlyLabel: 'سقف پیام در ساعت',
  hourlyHelp: 'کاربر رایگان در هر ساعت حداکثر این تعداد پیام می‌تواند بفرستد. با پایان ساعت دوباره باز می‌شود.',
  hourlySuffix: 'پیام / ساعت',
  lifetimeLabel: 'سقف پیام مادام‌العمر',
  lifetimeHelp: 'کل پیام‌هایی که یک کاربر رایگان در تمام عمر حسابش می‌تواند بفرستد. پس از رسیدن به این عدد، تا شارژ حساب مسدود می‌ماند (سقف سخت، در پایگاه داده نگهداری می‌شود).',
  lifetimeSuffix: 'پیام (کل)',
  maxInputLabel: 'سقف قیمت مدل‌های رایگان',
  maxInputHelp: 'کاربر رایگان فقط به مدل‌هایی دسترسی دارد که قیمت ورودی‌شان کمتر یا مساوی این عدد باشد (تومان بر میلیون توکن). مدل‌های گران‌تر برایش مسدودند تا هزینهٔ رایگان‌دهی کنترل شود.',
  maxInputSuffix: 'تومان / میلیون توکن',
  defaultValue: (n: string) => `(پیش‌فرض: ${n})`,
  invalidField: (label: string) => `«${label}» باید یک عدد صحیح نامنفی باشد.`,
  save: 'ذخیره',
  cancel: 'انصراف',
  noChanges: 'تغییری برای ذخیره وجود ندارد',
  saveSuccess: 'محدودیت‌های حساب رایگان ذخیره شد',
  saveError: 'ذخیره ناموفق بود',
  rowsMissing: (rows: string) => `ردیف‌های ذخیره‌سازی هنوز در پایگاه داده ساخته نشده‌اند (${rows}) — مهاجرت 0045 هنوز اعمال نشده است. مقادیر پیش‌فرض به‌کار می‌روند و اولین ذخیره ردیف را می‌سازد.`,
  listSeparator: '، ',
}

const EN: typeof FA = {
  title: 'Free tier',
  subtitle: 'Message caps and allowed models for users without a top-up',
  fullSubtitle: 'Hourly and lifetime message caps, and the price ceiling for models allowed to a user with no top-up and no package — no restart required',
  loadError: 'Failed to load free-tier settings',
  serverError: (status) => `Server error (${status})`,
  loadFailedTitle: 'Failed to load settings',
  retry: 'Retry',
  loading: 'Loading…',
  noData: 'No data found',
  hourlyLabel: 'Hourly message limit',
  hourlyHelp: 'The most messages a free-tier user can send per hour. Resets when the hour ends.',
  hourlySuffix: 'messages / hour',
  lifetimeLabel: 'Lifetime message limit',
  lifetimeHelp: 'The total messages a free-tier user can send over the lifetime of their account. Once reached, the account is blocked until it is topped up (a hard cap, stored in the database).',
  lifetimeSuffix: 'messages (total)',
  maxInputLabel: 'Free-tier model price ceiling',
  maxInputHelp: 'A free-tier user can only access models whose input price is at or below this number (Toman per million tokens). More expensive models are blocked to keep the cost of free serving under control.',
  maxInputSuffix: 'Toman / million tokens',
  defaultValue: (n) => `(default: ${n})`,
  invalidField: (label) => `"${label}" must be a non-negative integer.`,
  save: 'Save',
  cancel: 'Cancel',
  noChanges: 'No changes to save',
  saveSuccess: 'Free-tier limits saved',
  saveError: 'Save failed',
  rowsMissing: (rows) => `Storage rows for these do not exist in the database yet (${rows}) — migration 0045 has not been applied yet. Defaults are used until the first save creates the row.`,
  listSeparator: ', ',
}

export const freeTierStrings = dict(FA, EN)
