import { dict } from '@/lib/i18n'

const FA = {
  title: 'قیمت‌گذاری تصویر',
  subtitle: 'قیمت پایه (تومان) برای هر تصویر تولیدشده — مدل بدون قیمت هرگز به کاربر ارائه نمی‌شود',
  loadError: 'خطا در دریافت مدل‌های تصویری',
  saveErrorGeneric: 'ذخیره ناموفق بود',
  priceNotInteger: 'قیمت باید عدد صحیح تومان باشد (اعشار مجاز نیست)',
  priceNegative: 'قیمت نمی‌تواند منفی باشد',
  priceCleared: 'قیمت پاک شد — این مدل دیگر قابل ارائه نیست',
  priceSaved: 'قیمت این مدل ذخیره شد',
  unpriced: (n: string) => `${n} مدل تصویری بدون قیمت — تا قیمت‌گذاری نشوند قابل ارائه نیستند`,
  sectionTitle: 'مدل‌های تصویری',
  searchPlaceholder: 'جستجوی مدل…',
  colModel: 'مدل',
  colStatus: 'وضعیت',
  colBasePrice: 'قیمت پایه (تومان)',
  colMarkup: 'درصد سود',
  colMarkupSub: 'از تب «درصد سود»',
  colFinalPrice: 'قیمت نهایی هر تصویر',
  colNewPrice: 'قیمت جدید',
  colActions: 'عملیات',
  loading: 'در حال بارگذاری…',
  retry: 'تلاش دوباره',
  noModels: 'مدل تصویری یافت نشد',
  notSet: 'تعیین نشده',
  global: 'سراسری',
  noPricePlaceholder: 'بدون قیمت',
  saveTitleCleared: 'خالی = پاک کردن قیمت (مدل قابل ارائه نمی‌شود)',
  saveTitle: 'ذخیره قیمت',
}

const EN: typeof FA = {
  title: 'Image pricing',
  subtitle: 'Base price (Toman) per generated image — a model with no price is never served to users',
  loadError: 'Failed to load image models',
  saveErrorGeneric: 'Save failed',
  priceNotInteger: 'Price must be a whole number of Toman (no decimals allowed)',
  priceNegative: 'Price cannot be negative',
  priceCleared: 'Price cleared — this model can no longer be served',
  priceSaved: 'This model’s price was saved',
  unpriced: (n) => `${n} image model${n === '1' ? '' : 's'} with no price — cannot be served until priced`,
  sectionTitle: 'Image models',
  searchPlaceholder: 'Search model…',
  colModel: 'Model',
  colStatus: 'Status',
  colBasePrice: 'Base price (Toman)',
  colMarkup: 'Markup',
  colMarkupSub: 'from the "Markup" tab',
  colFinalPrice: 'Final price per image',
  colNewPrice: 'New price',
  colActions: 'Actions',
  loading: 'Loading…',
  retry: 'Retry',
  noModels: 'No image model found',
  notSet: 'Not set',
  global: 'Global',
  noPricePlaceholder: 'No price',
  saveTitleCleared: 'Empty = clear price (model becomes unservable)',
  saveTitle: 'Save price',
}

export const imagePricingStrings = dict(FA, EN)
