import { dict } from '@/lib/i18n'

const FA = {
  title: 'محتوای لندینگ',
  subtitle: 'بازنویسی متن صفحه‌ی فرود، بدون نیاز به دیپلوی. هر فیلد اختیاری است — خالی بماند یعنی همان متن پیش‌فرض نمایش داده می‌شود.',
  loadError: 'خطا در دریافت محتوای لندینگ',
  retry: 'تلاش دوباره',
  loading: 'در حال بارگذاری…',
  backendNotWiredHint: 'اگر این خطا با کد ۴۰۴ همراه است، یعنی مسیر بک‌اند هنوز به app.py وصل نشده — کار سنیور، نه یک خطای واقعی در این ماژول.',
  faColumn: 'فارسی',
  enColumn: 'انگلیسی',
  placeholderPrefix: 'پیش‌فرض:',
  save: 'ذخیره',
  saving: 'در حال ذخیره…',
  saveSuccess: (module: string) => `«${module}» ذخیره شد`,
  saveError: 'ذخیره ناموفق بود',
  resetToDefault: 'بازگشت به پیش‌فرض',
  resetting: 'در حال بازگشت…',
  resetSuccess: (module: string) => `«${module}» به پیش‌فرض بازگشت`,
  resetError: 'بازگشت به پیش‌فرض ناموفق بود',
  bothLanguagesRequired: 'برای هر فیلدی که پر می‌کنید، هر دو زبان (فارسی و انگلیسی) لازم است — یکی را خالی بگذارید یا هر دو را پر کنید.',
  nothingToSave: 'هیچ فیلدی برای ذخیره پر نشده — همه به پیش‌فرض برمی‌گردند',
  noEditableFields: 'این ماژول در حال حاضر هیچ فیلد ویرایش‌پذیری ندارد.',
  noEditableFieldsReasonCatalog: 'فهرست مدل‌های این بخش مستقیماً از کاتالوگ واقعی می‌آید؛ برای جلوگیری از نمایش نام یا لوگوی نادرست مدل، از پنل قابل ویرایش نیست.',
  noEditableFieldsReasonConstants: 'این دو مقدار فقط داخل بخش‌های دیگر (سوالات متداول، تعرفه‌ها، مراحل) درون‌ریزی می‌شوند و صفحه‌ی مستقلی برای نمایش ندارند — همان متن‌ها را از داخل همان بخش‌ها ویرایش کنید.',
  frozenFieldsNote: (paths: string) => `فیلدهای زیر از شمارش زنده‌ی مدل‌ها محاسبه می‌شوند و برای جلوگیری از نمایش عدد نادرست، از پنل ادمین قابل ویرایش نیستند: ${paths}`,
  listSeparator: '، ',
  fieldCount: (n: string) => `${n} فیلد قابل ویرایش`,
  updatedAt: (date: string) => `آخرین ذخیره: ${date}`,
  neverUpdated: 'هنوز ذخیره نشده — متن پیش‌فرض نمایش داده می‌شود',
  moduleNames: {
    api: 'بخش API',
    capabilities: 'نمایش قابلیت‌ها',
    catalog: 'مارکی مدل‌ها',
    comparison: 'جدول مقایسه',
    constants: 'ثابت‌های عمومی',
    faq: 'سوالات متداول',
    features: 'شبکه‌ی امکانات',
    footer: 'فوتر',
    hero: 'بخش قهرمان (بالای صفحه)',
    nav: 'نوار ناوبری',
    pricing: 'بخش تعرفه‌ها',
    stats: 'نوار آمار',
    steps: 'مراحل شروع کار',
  },
}

const EN: typeof FA = {
  title: 'Landing content',
  subtitle: 'Override the landing page copy without a deploy. Every field is optional — leave it blank to keep showing the default text.',
  loadError: 'Failed to load landing content',
  retry: 'Try again',
  loading: 'Loading…',
  backendNotWiredHint: 'If this error carries a 404, the backend route is not yet wired into app.py — that is the senior\'s job, not a real bug in this module.',
  faColumn: 'Persian',
  enColumn: 'English',
  placeholderPrefix: 'Default:',
  save: 'Save',
  saving: 'Saving…',
  saveSuccess: (module) => `"${module}" saved`,
  saveError: 'Failed to save',
  resetToDefault: 'Reset to default',
  resetting: 'Resetting…',
  resetSuccess: (module) => `"${module}" reset to default`,
  resetError: 'Failed to reset to default',
  bothLanguagesRequired: 'Any field you fill in needs both languages (Persian and English) — leave both blank, or fill in both.',
  nothingToSave: 'No field is filled in — everything will fall back to the default',
  noEditableFields: 'This module currently has no editable fields.',
  noEditableFieldsReasonCatalog: 'This section\'s model list comes straight from the real catalog; it is not editable from the panel, to avoid showing a wrong model name or logo.',
  noEditableFieldsReasonConstants: 'These two values are only inlined into other modules\' copy (FAQ, pricing, steps) and have no page of their own to render — edit the same text from within those modules instead.',
  frozenFieldsNote: (paths) => `The following fields are computed from the live model count and are not editable from the admin panel, to avoid showing a wrong number: ${paths}`,
  listSeparator: ', ',
  fieldCount: (n) => `${n} editable field${n === '1' ? '' : 's'}`,
  updatedAt: (date) => `Last saved: ${date}`,
  neverUpdated: 'Never saved — showing the default text',
  moduleNames: {
    api: 'API section',
    capabilities: 'Capability showcase',
    catalog: 'Model marquee',
    comparison: 'Comparison table',
    constants: 'Global constants',
    faq: 'FAQ',
    features: 'Feature grid',
    footer: 'Footer',
    hero: 'Hero (top of page)',
    nav: 'Navigation bar',
    pricing: 'Pricing section',
    stats: 'Stats band',
    steps: 'Getting-started steps',
  },
}

export const landingContentStrings = dict(FA, EN)
