import { dict } from '@/lib/i18n'

const FA = {
  routing: {
    cheapest_healthy: 'ارزان‌ترین سالم',
    priority: 'بر اساس اولویت',
    pinned: 'پین‌شده',
  },
  state: {
    proposed: 'بررسی‌نشده',
    approved: 'تأییدشده',
    rejected: 'ردشده',
  },
  loadListError: 'خطا در دریافت فهرست مدل‌های منطقی',
  loadDetailError: 'خطا در دریافت جزئیات مدل',
  saveFailed: 'ذخیره ناموفق بود',
  candidateApproved: 'گزینه تأیید شد',
  candidateRejected: 'گزینه رد شد',
  candidateEnabled: 'گزینه فعال شد',
  candidateDisabled: 'گزینه غیرفعال شد',
  prioritySaved: 'اولویت ذخیره شد',
  candidatePinned: 'گزینه پین شد',
  pinRemoved: 'پین برداشته شد',
  routingSaved: 'سیاست مسیریابی ذخیره شد',
  availabilitySaved: 'وضعیت در دسترس‌بودن ذخیره شد',
  title: 'مدل‌های منطقی',
  subtitle: 'بررسی و تأیید گزینه‌های فیزیکی هر مدل منطقی — صف کار: مدل‌هایی که گزینهٔ بررسی‌نشده دارند',
  statTotal: 'کل مدل‌های منطقی',
  statPending: 'در این صفحه، دارای گزینهٔ بررسی‌نشده',
  statApproved: 'کل گزینه‌های تأییدشده (نمونه‌گیری صفحه)',
  searchPlaceholder: 'جستجوی کلید یا نام نمایشی…',
  allAvailability: 'همهٔ وضعیت‌ها',
  pendingOnlyLabel: 'فقط مدل‌های دارای گزینهٔ بررسی‌نشده (صف کار)',
  colLogicalModel: 'مدل منطقی',
  colVendor: 'فروشنده',
  colStatus: 'وضعیت',
  colRoutingPolicy: 'سیاست مسیریابی',
  colCandidateCounts: 'گزینه‌ها (بررسی‌نشده / تأیید / رد)',
  colActions: 'عملیات',
  loadingRow: 'در حال بارگذاری…',
  noneFound: 'موردی یافت نشد',
  review: 'بررسی',
  close: 'بستن',
  footer: (total: string, page: string, totalPages: string) => `${total} مدل — صفحهٔ ${page} از ${totalPages}`,
  prev: 'قبلی',
  next: 'بعدی',
  loadingDetail: 'در حال بارگذاری جزئیات…',
  routingPolicyLabel: 'سیاست مسیریابی: ',
  availabilityLabel: 'وضعیت در دسترس‌بودن: ',
  currentPinLabel: 'پین فعلی: ',
  removePin: 'برداشتن پین',
  noPin: 'ندارد',
  colPhysicalModel: 'مدل فیزیکی',
  colProviderStatus: 'وضعیت پروایدر',
  colPriceTomanMillion: 'قیمت (تومان / میلیون توکن)',
  colUsdEstimate: 'برآورد دلاری',
  colCandidateState: 'وضعیت گزینه',
  colEnabled: 'فعال',
  colPriority: 'اولویت',
  noCandidates: 'گزینه‌ای ثبت نشده است',
  inputLabel: 'ورودی: ',
  outputLabel: 'خروجی: ',
  perMillionIn: '/ M in',
  perMillionOut: '/ M out',
  approveTitle: 'تأیید',
  rejectTitle: 'رد',
  resetTitle: 'بازگردانی به بررسی‌نشده',
  pinned: 'پین‌شده',
  pin: 'پین',
  pinEligibleTitle: 'پین کردن این گزینه',
  pinIneligibleTitle: 'فقط گزینهٔ تأییدشده و فعال قابل پین است',
}

const EN: typeof FA = {
  routing: {
    cheapest_healthy: 'Cheapest healthy',
    priority: 'By priority',
    pinned: 'Pinned',
  },
  state: {
    proposed: 'Proposed',
    approved: 'Approved',
    rejected: 'Rejected',
  },
  loadListError: 'Failed to fetch the logical models list',
  loadDetailError: 'Failed to fetch the model details',
  saveFailed: 'Save failed',
  candidateApproved: 'Candidate approved',
  candidateRejected: 'Candidate rejected',
  candidateEnabled: 'Candidate enabled',
  candidateDisabled: 'Candidate disabled',
  prioritySaved: 'Priority saved',
  candidatePinned: 'Candidate pinned',
  pinRemoved: 'Pin removed',
  routingSaved: 'Routing policy saved',
  availabilitySaved: 'Availability status saved',
  title: 'Logical Models',
  subtitle: 'Review and approve the physical candidates of each logical model — the queue is models with an unreviewed candidate',
  statTotal: 'Total logical models',
  statPending: 'On this page, with an unreviewed candidate',
  statApproved: 'Total approved candidates (page sample)',
  searchPlaceholder: 'Search key or display name…',
  allAvailability: 'All statuses',
  pendingOnlyLabel: 'Only models with an unreviewed candidate (queue)',
  colLogicalModel: 'Logical model',
  colVendor: 'Vendor',
  colStatus: 'Status',
  colRoutingPolicy: 'Routing policy',
  colCandidateCounts: 'Candidates (proposed / approved / rejected)',
  colActions: 'Actions',
  loadingRow: 'Loading…',
  noneFound: 'Nothing found',
  review: 'Review',
  close: 'Close',
  footer: (total, page, totalPages) => `${total} models — page ${page} of ${totalPages}`,
  prev: 'Previous',
  next: 'Next',
  loadingDetail: 'Loading details…',
  routingPolicyLabel: 'Routing policy: ',
  availabilityLabel: 'Availability status: ',
  currentPinLabel: 'Current pin: ',
  removePin: 'Remove pin',
  noPin: 'None',
  colPhysicalModel: 'Physical model',
  colProviderStatus: 'Provider status',
  colPriceTomanMillion: 'Price (Toman / million tokens)',
  colUsdEstimate: 'USD estimate',
  colCandidateState: 'Candidate state',
  colEnabled: 'Enabled',
  colPriority: 'Priority',
  noCandidates: 'No candidates recorded',
  inputLabel: 'Input: ',
  outputLabel: 'Output: ',
  perMillionIn: '/ M in',
  perMillionOut: '/ M out',
  approveTitle: 'Approve',
  rejectTitle: 'Reject',
  resetTitle: 'Reset to proposed',
  pinned: 'Pinned',
  pin: 'Pin',
  pinEligibleTitle: 'Pin this candidate',
  pinIneligibleTitle: 'Only an approved and enabled candidate can be pinned',
}

export const logicalModelsStrings = dict(FA, EN)
