import { dict } from '@/lib/adminI18n'

const FA = {
  loadError: 'خطا در دریافت فهرست کاتالوگ — اتصال یا سرور مشکل دارد.',
  selectAtLeastOne: 'ابتدا حداقل یک مدل را انتخاب کنید',
  bulkApplied: (n: string, label: string) => `وضعیت ${n} مدل به «${label}» تغییر کرد`,
  bulkFailed: 'اعمال گروهی ناموفق بود',
  toggleSuccess: 'وضعیت مدل تغییر کرد',
  toggleFailed: 'تغییر وضعیت ناموفق بود',
  testSuccess: (ms: string) => `تست موفق — تأخیر ${ms} میلی‌ثانیه`,
  testFailed: (error: string) => `تست ناموفق: ${error}`,
  unknownError: 'خطای نامشخص',
  testFailedGeneric: 'اجرای تست انجام نشد (خطای شبکه یا سرور)',
  upstreamEmpty: 'نام upstream نمی‌تواند خالی باشد',
  upstreamSaved: 'upstream این مدل تغییر کرد',
  upstreamFailed: 'تغییر upstream ناموفق بود — نام باید یکی از تأمین‌کننده‌های پیکربندی‌شده باشد',
  title: 'عملیات کاتالوگ مدل‌ها',
  subtitle: (total: string, available: string) => `${total} ردیف کاتالوگ — تنها ${available} مورد «در دسترس»`,
  warning1: 'سرور اجازهٔ «در دسترس» کردن مدلی که هرگز «تست زنده» موفق نداشته را نمی‌دهد و این درخواست را با نام همان مدل‌ها رد می‌کند.',
  warning2: 'مدل‌ها را انتخاب کنید و «تست زندهٔ گروهی» را بزنید؛ هر تست موفق همان‌جا ثبت می‌شود و مدل را برای فعال‌سازی واجد شرایط می‌کند.',
  selectedCount: (n: string) => `${n} مدل انتخاب شده`,
  selectAllFiltered: (n: string) => `انتخاب همهٔ ${n} مورد فیلترشده`,
  deselectPage: 'لغو انتخاب این صفحه',
  selectPage: 'انتخاب این صفحه',
  clearSelection: 'پاک کردن انتخاب',
  bulkChangeLabel: 'تغییر گروهی وضعیت به:',
  applyBulk: 'اعمال گروهی',
  bulkLiveTest: 'تست زندهٔ گروهی',
  colModel: 'مدل',
  colStatus: 'وضعیت',
  colProvider: 'تأمین‌کننده / upstream',
  colContext: 'پنجرهٔ متن',
  colPrice: 'قیمت (ورودی / خروجی هر میلیون)',
  colProbe: 'پروب زندهٔ موفق',
  colActions: 'عملیات',
  loadingRow: 'در حال بارگذاری…',
  retry: 'تلاش دوباره',
  noModelsFound: 'مدلی با این فیلتر یافت نشد',
  disableAction: 'غیرفعال کن',
  enableAction: 'در دسترس کن',
  toggleHint: 'این کلید سریع فقط بین «در دسترس» و «غیرفعال» جابه‌جا می‌کند',
  useBulkInstead: 'برای این وضعیت، از «تغییر گروهی» در بالای صفحه استفاده کنید',
  changeUpstreamTitle: 'تغییر upstream',
  healthyUnserved: 'سالم ولی ارائه‌نشده',
  noPublicId: 'بدون شناسهٔ عمومی — برای کاربر دیده نمی‌شود',
  never: 'هرگز',
  testLive: 'تست زنده',
  healthyLatency: (ms: string) => `سالم — ${ms}ms`,
  errorFallback: 'خطا',
  pageOf: (page: string, total: string) => `صفحهٔ ${page} از ${total}`,
  prev: 'قبلی',
  next: 'بعدی',
  confirmModalTitle: 'تأیید تغییر گروهی وضعیت',
  confirmModalBody: (n: string, label: string) => `وضعیت ${n} مدل به «${label}» تغییر می‌کند.`,
  confirmModalWarning: 'سرور مدل‌هایی که «تست زنده» موفق نداشته‌اند را رد می‌کند — اگر برخی از انتخاب‌ها هنوز تست نشده باشند، این عملیات با خطا و نام همان مدل‌ها برمی‌گردد.',
  confirmApply: 'تأیید و اعمال',
  applying: 'در حال اعمال...',
  cancel: 'انصراف',
}

const EN: typeof FA = {
  loadError: 'Failed to fetch the catalog — connection or server error.',
  selectAtLeastOne: 'Select at least one model first',
  bulkApplied: (n, label) => `${n} model status changed to "${label}"`,
  bulkFailed: 'Bulk apply failed',
  toggleSuccess: 'Model status changed',
  toggleFailed: 'Status change failed',
  testSuccess: (ms) => `Test succeeded — latency ${ms}ms`,
  testFailed: (error) => `Test failed: ${error}`,
  unknownError: 'Unknown error',
  testFailedGeneric: 'Test did not run (network or server error)',
  upstreamEmpty: 'Upstream name cannot be empty',
  upstreamSaved: 'This model\'s upstream was changed',
  upstreamFailed: 'Upstream change failed — the name must be one of the configured providers',
  title: 'Model Catalog Operations',
  subtitle: (total, available) => `${total} catalog rows — only ${available} "Available"`,
  warning1: 'The server refuses to mark a model "Available" if it has never had a successful live test, and rejects the request naming those models.',
  warning2: 'Select models and click "Bulk live test"; every successful test is recorded there and makes the model eligible to enable.',
  selectedCount: (n) => `${n} models selected`,
  selectAllFiltered: (n) => `Select all ${n} filtered`,
  deselectPage: 'Deselect this page',
  selectPage: 'Select this page',
  clearSelection: 'Clear selection',
  bulkChangeLabel: 'Bulk change status to:',
  applyBulk: 'Apply to selection',
  bulkLiveTest: 'Bulk live test',
  colModel: 'Model',
  colStatus: 'Status',
  colProvider: 'Provider / upstream',
  colContext: 'Context window',
  colPrice: 'Price (input / output per million)',
  colProbe: 'Successful live probe',
  colActions: 'Actions',
  loadingRow: 'Loading…',
  retry: 'Retry',
  noModelsFound: 'No model matches this filter',
  disableAction: 'Disable',
  enableAction: 'Make available',
  toggleHint: 'This quick toggle only switches between Available and Disabled',
  useBulkInstead: 'For this status, use "Bulk change" at the top of the page',
  changeUpstreamTitle: 'Change upstream',
  healthyUnserved: 'Healthy but unserved',
  noPublicId: 'No public id — invisible to users',
  never: 'Never',
  testLive: 'Live test',
  healthyLatency: (ms) => `Healthy — ${ms}ms`,
  errorFallback: 'Error',
  pageOf: (page, total) => `Page ${page} of ${total}`,
  prev: 'Previous',
  next: 'Next',
  confirmModalTitle: 'Confirm bulk status change',
  confirmModalBody: (n, label) => `${n} model status will change to "${label}".`,
  confirmModalWarning: 'The server rejects models that have not had a successful live test — if some of the selection is still untested, this operation will fail and name those models.',
  confirmApply: 'Confirm and apply',
  applying: 'Applying...',
  cancel: 'Cancel',
}

export const modelOpsStrings = dict(FA, EN)
