import { dict } from '@/lib/i18n'

const FA = {
  title: 'بسته‌های اعتباری',
  subtitle: (n: string) => `${n} بسته — پرداختی، اعتبار واریزی، سهمیهٔ درخواست/توکن و سقف پیام ۵ ساعته چهار عدد جداگانه‌اند`,
  loadError: 'خطا در دریافت بسته‌ها',
  nameRequired: 'نام فارسی و انگلیسی الزامی است',
  lossPathToastMessage: 'بسته‌ای که سهمیهٔ درخواست یا توکن دارد باید سقف هزینهٔ هر درخواست هم داشته باشد، وگرنه مسیر ضررده است',
  saved: 'بسته ذخیره شد',
  saveError: 'ذخیره ناموفق بود',
  idRequired: 'شناسهٔ بسته الزامی است',
  created: 'بستهٔ جدید ایجاد شد',
  createError: 'ایجاد بسته ناموفق بود',

  fourNumbersTitle: 'چهار عدد، چهار معنای متفاوت',
  bulletPaid: 'مبلغ پرداختی',
  bulletPaidText: ' (base_amount): مبلغی که کاربر واقعاً پرداخت می‌کند.',
  bulletCredited: 'مبلغ واریزی به کیف پول',
  bulletCreditedText: ' (total_credits): مبلغ نهایی (شامل پاداش) که به کیف پول کاربر اضافه می‌شود — این عدد از قبل شامل پاداش است، جمع‌کردن درصد پاداش رویش دوباره اشتباه است.',
  bulletQuota: 'سهمیهٔ درخواست/توکن',
  bulletQuotaText: ': عددی کاملاً جدا از تومان — تعداد کل درخواست یا توکنی که این بسته می‌خرد و به کاربر سهمیهٔ مستقل از کیف پول می‌دهد.',
  bulletRateLimit: 'سقف پیام ۵ ساعته',
  bulletRateLimitText: ': محدودیت نرخ ارسال پیام، ربطی به سهمیهٔ بالا ندارد — کیف پول همیشه هزینهٔ این پیام‌ها را می‌پردازد؛ فقط تعداد پیام در هر پنجرهٔ ۵ ساعته را محدود می‌کند. ستون «از این، روی مدل گران» زیرمجموعهٔ همین سقف است، نه عددی جدا و اضافه.',
  lossPathWarning: '🔴 بسته‌ای که سهمیهٔ درخواست یا توکن دارد باید «سقف هزینهٔ هر درخواست» هم داشته باشد — وگرنه کاربر می‌تواند کل سهمیه را روی گران‌ترین مدل خرج کند و هر درخواست ضررده شود. سرور این را رد می‌کند؛ این فرم فقط از قبل هشدار می‌دهد. سقف پیام ۵ ساعته و زیرمجموعهٔ آن روی مدل گران این قاعده را ندارند، چون کیف پول همیشه پرداخت می‌کند.',

  colPackage: 'بسته',
  colActive: 'فعال',
  colBaseAmount: 'مبلغ پرداختی',
  colTotalCredits: 'مبلغ واریزی به کیف پول',
  colBonusPercent: 'درصد پاداش',
  colRequestQuota: 'سهمیهٔ درخواست',
  colTokenQuota: 'سهمیهٔ توکن',
  colMaxCostPerRequest: 'سقف هزینهٔ هر درخواست',
  colRateLimit: 'سقف پیام',
  colRateLimitSub: '۵ ساعته',
  colPremiumRateLimit: 'از این، روی مدل گران',
  colPremiumRateLimitTitle: 'زیرمجموعهٔ ستون «سقف پیام» است، نه عددی جدا و اضافه',
  colValidityDays: 'مدت اعتبار (روز)',
  colActions: 'عملیات',

  loading: 'در حال بارگذاری…',
  retry: 'تلاش دوباره',
  noPackages: 'بسته‌ای یافت نشد',
  premiumFootnote: '«از این، روی مدل گران» از داخل «سقف پیام» شمرده می‌شود، نه اضافه بر آن — مثلاً کاربری با ۴۰ و ۵، در هر پنجرهٔ ۵ ساعته حداکثر ۴۰ پیام می‌فرستد که حداکثر ۵ تای آن‌ها می‌تواند روی مدل‌های گران باشد.',
  closeCreateForm: 'بستن فرم بستهٔ جدید',
  openCreateForm: '+ افزودن بسته',
}

const EN: typeof FA = {
  title: 'Credit packages',
  subtitle: (n) => `${n} packages — amount paid, credited amount, request/token quota and the 5-hour message cap are four separate numbers`,
  loadError: 'Failed to load packages',
  nameRequired: 'Persian and English name are required',
  lossPathToastMessage: 'A package with a request or token quota must also have a per-request cost ceiling, otherwise it is loss-making',
  saved: 'Package saved',
  saveError: 'Save failed',
  idRequired: 'Package id is required',
  created: 'New package created',
  createError: 'Failed to create package',

  fourNumbersTitle: 'Four numbers, four different meanings',
  bulletPaid: 'Amount paid',
  bulletPaidText: ' (base_amount): the amount the buyer actually pays.',
  bulletCredited: 'Amount credited to wallet',
  bulletCreditedText: ' (total_credits): the final amount (including any bonus) added to the buyer’s wallet — this number already includes the bonus, adding the bonus percent to it again is a mistake.',
  bulletQuota: 'Request/token quota',
  bulletQuotaText: ': a number entirely separate from Toman — the total count of requests or tokens this package buys, granting the user a quota independent of the wallet.',
  bulletRateLimit: '5-hour message cap',
  bulletRateLimitText: ': a message send-rate limit, unrelated to the quota above — the wallet always pays for these messages; this only limits how many messages fit in each 5-hour window. The "of which, on premium models" column is a subset of this cap, not a separate additional number.',
  lossPathWarning: '🔴 A package with a request or token quota must also have a "per-request cost ceiling" — otherwise the user could spend the whole quota on the most expensive model and make every request loss-making. The server rejects this; this form only warns in advance. The 5-hour message cap and its premium-model subset are not subject to this rule, because the wallet always pays for them.',

  colPackage: 'Package',
  colActive: 'Active',
  colBaseAmount: 'Amount paid',
  colTotalCredits: 'Amount credited to wallet',
  colBonusPercent: 'Bonus percent',
  colRequestQuota: 'Request quota',
  colTokenQuota: 'Token quota',
  colMaxCostPerRequest: 'Max cost per request',
  colRateLimit: 'Message cap',
  colRateLimitSub: '5-hour',
  colPremiumRateLimit: 'Of which, on premium models',
  colPremiumRateLimitTitle: 'A subset of the "message cap" column, not a separate additional number',
  colValidityDays: 'Validity (days)',
  colActions: 'Actions',

  loading: 'Loading…',
  retry: 'Retry',
  noPackages: 'No package found',
  premiumFootnote: '"Of which, on premium models" is counted from inside the "message cap", not on top of it — e.g. a user with 40 and 5 sends at most 40 messages per 5-hour window, of which at most 5 can be on premium models.',
  closeCreateForm: 'Close new package form',
  openCreateForm: '+ Add package',
}

export const packagesSectionStrings = dict(FA, EN)
