import { dict } from '@/lib/adminI18n'

const FA = {
  headerTitle: 'پلن‌ها و اشتراک‌ها',
  headerSubtitle: (plans: string, subs: string) => `${plans} پلن — ${subs} اشتراک ثبت‌شده`,
  loadPlansError: 'خطا در دریافت پلن‌ها',
  loadSubsError: 'خطا در دریافت اشتراک‌ها',
  nameRequired: 'نام فارسی و انگلیسی الزامی است',
  planSaved: 'پلن ذخیره شد',
  planSaveError: 'ذخیره پلن ناموفق بود',
  planIdRequired: 'شناسهٔ پلن الزامی است',
  planCreated: 'پلن جدید ایجاد شد',
  planCreateError: 'ایجاد پلن ناموفق بود',

  // The «هیچ مدل رایگانی نداریم» warning card. Broken into segments (rather
  // than one interpolated sentence) because the id, the price and the quota
  // are each wrapped in their own <b> in the JSX -- see PlansSection.tsx.
  freeConflictTitle: 'تناقض با قاعدهٔ محصول: «هیچ مدل رایگانی نداریم»',
  freeConflictIdPrefix: 'پلن با شناسهٔ',
  freeConflictExists: 'در دیتابیس زنده وجود دارد: قیمت ماهانه =',
  freeConflictQuotaLabel: '، سهمیهٔ توکن ماهانه (monthly_token_quota) =',
  freeConflictTokenUnit: 'توکن',
  freeConflictLegacyNote: (v: string) => `(ستون قدیمی token_quota_monthly = ${v})`,
  freeConflictIsDefault: '، is_default =',
  yes: 'بله',
  no: 'خیر',
  freeConflictExplain: 'طبق قاعدهٔ محصول هیچ مدلی رایگان نیست — حتی تأمین رایگان هم پولی فروخته می‌شود. این پلن حذف یا خودکار ویرایش نشد؛ فقط اینجا برجسته شده تا مالک محصول تصمیم بگیرد (غیرفعال کردن، تغییر قیمت، یا حذفش).',

  colPlan: 'پلن',
  colActive: 'فعال',
  colPriceMonthly: 'قیمت ماهانه',
  colMonthlyQuota: 'سهمیهٔ توکن ماهانه',
  colDailyCap: 'سقف روزانه',
  colPriorityQueue: 'صف اولویت',
  colSortOrder: 'ترتیب نمایش',
  colActions: 'عملیات',

  loading: 'در حال بارگذاری…',
  retry: 'تلاش دوباره',
  noPlans: 'پلنی یافت نشد',
  namePlaceholderFa: 'نام فارسی',
  namePlaceholderEn: 'نام انگلیسی',
  defaultSuffix: ' · پیش‌فرض',
  hideDetails: 'بستن جزئیات',
  showDetails: 'نمایش جزئیات',
  save: 'ذخیره',

  detailDescription: (v: string) => `توضیحات: ${v}`,
  detailYearlyPrice: (v: string) => `قیمت سالانه (price_yearly): ${v}`,
  detailLegacyQuota: (v: string) => `ستون قدیمی token_quota_monthly: ${v} — اکنون همیشه هم‌زمان با monthly_token_quota ذخیره می‌شود و نباید از آن واگرا شود.`,
  detailFeatures: (v: string) => `امکانات (features، فقط نمایش): ${v}`,
  detailModelsAllowed: (v: string) => `مدل‌های مجاز (models_allowed، فقط نمایش): ${v}`,
  detailUnlimited: 'بدون محدودیت',
  // Used to .join() a features/models_allowed array -- kept in the
  // dictionary (rather than a `lang === 'en' ? ', ' : '، '` inline ternary)
  // so no raw Persian character sits in PlansSection.tsx itself.
  listSeparator: '، ',
  detailCreatedUpdated: (created: string, updated: string) => `ایجاد: ${created} — به‌روزرسانی: ${updated}`,

  closeCreateForm: 'بستن فرم پلن جدید',
  openCreateForm: '+ ایجاد پلن جدید',
  // Broken into segments rather than one JSX blob: `name`/`price_yearly`/
  // `token_quota_monthly` are rendered as separate <code dir="ltr"> spans
  // in PlansSection.tsx, and JSX cannot live in a .strings.ts file.
  createFormIntroBefore: 'ستون‌های الزامی',
  createFormIntroSep: '،',
  createFormIntroAnd: 'و',
  createFormIntroAfter: 'توسط بک‌اند به‌صورت خودکار مقداردهی می‌شوند (قیمت سالانه پیش‌فرض = ۱۲ برابر قیمت ماهانه، مگر جای دیگری تعیین شود).',
  fieldId: 'شناسه (id)',
  fieldNameFa: 'نام فارسی',
  fieldNameEn: 'نام انگلیسی',
  fieldPriceMonthly: 'قیمت ماهانه',
  fieldMonthlyQuota: 'سهمیهٔ توکن ماهانه',
  fieldDailyCap: 'سقف روزانه',
  creating: 'در حال ایجاد...',
  createPlan: 'ایجاد پلن',

  subsTitle: 'اشتراک‌های کاربران',
  colUser: 'کاربر',
  colStatus: 'وضعیت',
  colQuota: 'سهمیهٔ توکن',
  colUsedTokens: 'توکن مصرف‌شده',
  colPricePaid: 'مبلغ پرداختی',
  colAutoRenew: 'تمدید خودکار',
  colCreatedAt: 'تاریخ ایجاد',
  noSubs: 'هیچ اشتراکی ثبت نشده (خروجی زندهٔ سرور: total = ۰)',
  subsPage: (page: string, totalPages: string, total: string) => `صفحهٔ ${page} از ${totalPages} (${total} اشتراک)`,
  prev: 'قبلی',
  next: 'بعدی',
}

const EN: typeof FA = {
  headerTitle: 'Plans & Subscriptions',
  headerSubtitle: (plans, subs) => `${plans} plans — ${subs} subscriptions on record`,
  loadPlansError: 'Failed to load plans',
  loadSubsError: 'Failed to load subscriptions',
  nameRequired: 'Persian and English name are required',
  planSaved: 'Plan saved',
  planSaveError: 'Failed to save plan',
  planIdRequired: 'Plan id is required',
  planCreated: 'New plan created',
  planCreateError: 'Failed to create plan',

  freeConflictTitle: 'Conflicts with the product rule: "We have no free models"',
  freeConflictIdPrefix: 'A plan with id',
  freeConflictExists: 'exists in the live database: monthly price =',
  freeConflictQuotaLabel: ', monthly token quota (monthly_token_quota) =',
  freeConflictTokenUnit: 'tokens',
  freeConflictLegacyNote: (v) => `(legacy column token_quota_monthly = ${v})`,
  freeConflictIsDefault: ', is_default =',
  yes: 'Yes',
  no: 'No',
  freeConflictExplain: 'Per the product rule no model is free — even the free upstream is sold for money. This plan was not deleted or auto-edited; it is only highlighted here so the product owner can decide (disable it, change the price, or delete it).',

  colPlan: 'Plan',
  colActive: 'Active',
  colPriceMonthly: 'Monthly price',
  colMonthlyQuota: 'Monthly token quota',
  colDailyCap: 'Daily cap',
  colPriorityQueue: 'Priority queue',
  colSortOrder: 'Sort order',
  colActions: 'Actions',

  loading: 'Loading…',
  retry: 'Retry',
  noPlans: 'No plan found',
  namePlaceholderFa: 'Persian name',
  namePlaceholderEn: 'English name',
  defaultSuffix: ' · default',
  hideDetails: 'Hide details',
  showDetails: 'Show details',
  save: 'Save',

  detailDescription: (v) => `Description: ${v}`,
  detailYearlyPrice: (v) => `Yearly price (price_yearly): ${v}`,
  detailLegacyQuota: (v) => `Legacy column token_quota_monthly: ${v} — now always written together with monthly_token_quota and must not diverge from it.`,
  detailFeatures: (v) => `Features (features, display only): ${v}`,
  detailModelsAllowed: (v) => `Allowed models (models_allowed, display only): ${v}`,
  detailUnlimited: 'Unrestricted',
  listSeparator: ', ',
  detailCreatedUpdated: (created, updated) => `Created: ${created} — updated: ${updated}`,

  closeCreateForm: 'Close new plan form',
  openCreateForm: '+ Create new plan',
  createFormIntroBefore: 'The required columns',
  createFormIntroSep: ',',
  createFormIntroAnd: 'and',
  createFormIntroAfter: 'are set automatically by the backend (yearly price defaults to 12x the monthly price, unless set otherwise).',
  fieldId: 'Id',
  fieldNameFa: 'Persian name',
  fieldNameEn: 'English name',
  fieldPriceMonthly: 'Monthly price',
  fieldMonthlyQuota: 'Monthly token quota',
  fieldDailyCap: 'Daily cap',
  creating: 'Creating...',
  createPlan: 'Create plan',

  subsTitle: 'User subscriptions',
  colUser: 'User',
  colStatus: 'Status',
  colQuota: 'Token quota',
  colUsedTokens: 'Tokens used',
  colPricePaid: 'Amount paid',
  colAutoRenew: 'Auto-renew',
  colCreatedAt: 'Created at',
  noSubs: 'No subscription on record (live server response: total = 0)',
  subsPage: (page, totalPages, total) => `Page ${page} of ${totalPages} (${total} subscriptions)`,
  prev: 'Previous',
  next: 'Next',
}

export const plansStrings = dict(FA, EN)
