import { dict } from '@/lib/i18n'

const FA = {
  title: 'مدیریت تعرفه‌ها',
  subtitle: 'قیمت‌گذاری مدل‌ها به ازای هر میلیون توکن',
  genericError: 'خطا در دریافت تعرفه‌ها',
  searchPlaceholder: 'جستجوی مدل…',
  matched: (shown: string, total: string) => `${shown} از ${total} مدل`,
  colModel: 'مدل',
  colInput: 'ورودی (تومان/میلیون)',
  colOutput: 'خروجی (تومان/میلیون)',
  colUnit: 'واحد',
  colStatus: 'وضعیت',
  colTest: 'تست',
  colActions: 'عملیات',
  noPricing: 'تعرفه‌ای ثبت نشده',
  noMatch: 'موردی با این جستجو یافت نشد',
  inputPlaceholder: 'تومان/میلیون',
  inputAriaLabel: (model: string) => `قیمت ورودی ${model} به تومان بر میلیون توکن`,
  outputAriaLabel: (model: string) => `قیمت خروجی ${model} به تومان بر میلیون توکن`,
  toggleTitle: 'کلیک برای تغییر وضعیت',
  toggleDisabledTitle: 'برای تغییر وضعیت این مدل از تب «عملیات کاتالوگ» استفاده کنید',
  test: 'تست',
  testError: 'خطا',
  save: 'ذخیره',
  cancel: 'انصراف',
  editTitle: 'ویرایش تعرفه',
  pageRange: (start: string, end: string, total: string, page: string, totalPages: string) =>
    `${start}–${end} از ${total} مدل — صفحهٔ ${page} از ${totalPages}`,
  prev: 'قبلی',
  next: 'بعدی',
  footerNote: 'برای ساخت و ویرایش بسته‌های اعتباری از صفحه «بسته‌ها» استفاده کنید؛ تنها آن صفحه پیش از انتشار، ضررده نبودن بسته را بررسی می‌کند.',
  modelEnabled: (model: string) => `${model} فعال شد`,
  modelDisabled: (model: string) => `${model} غیرفعال شد`,
  toggleError: 'خطا در تغییر وضعیت مدل',
  testModelError: 'خطا در تست مدل',
  testResponded: (model: string, ms: string) => `${model} پاسخ داد (${ms}ms)`,
  testFailed: (model: string, reason: string) => `${model} پاسخ نداد: ${reason}`,
  testUnknownReason: 'نامشخص',
  saveOk: 'تعرفه ذخیره شد',
  saveError: 'خطا در ذخیره تعرفه',
  priceEmpty: (label: string) => `قیمت ${label} نمی‌تواند خالی باشد`,
  priceNotNumber: (label: string) => `قیمت ${label} باید یک عدد باشد`,
  priceNegative: (label: string) => `قیمت ${label} نمی‌تواند منفی باشد`,
  priceNotInteger: (label: string) => `قیمت ${label} باید عدد صحیح (تومان) باشد`,
  fieldInput: 'ورودی',
  fieldOutput: 'خروجی',
  currencyIrt: 'تومان',
  currencyIrr: 'ریال',
}

const EN: typeof FA = {
  title: 'Tariff management',
  subtitle: 'Model pricing per million tokens',
  genericError: 'Failed to load tariffs',
  searchPlaceholder: 'Search model…',
  matched: (shown, total) => `${shown} of ${total} models`,
  colModel: 'Model',
  colInput: 'Input (Toman/million)',
  colOutput: 'Output (Toman/million)',
  colUnit: 'Unit',
  colStatus: 'Status',
  colTest: 'Test',
  colActions: 'Actions',
  noPricing: 'No tariffs registered',
  noMatch: 'No match for this search',
  inputPlaceholder: 'Toman/million',
  inputAriaLabel: (model) => `${model} input price in Toman per million tokens`,
  outputAriaLabel: (model) => `${model} output price in Toman per million tokens`,
  toggleTitle: 'Click to change status',
  toggleDisabledTitle: 'To change this model’s status use the "Catalog operations" tab',
  test: 'Test',
  testError: 'Error',
  save: 'Save',
  cancel: 'Cancel',
  editTitle: 'Edit tariff',
  pageRange: (start, end, total, page, totalPages) =>
    `${start}–${end} of ${total} models — page ${page} of ${totalPages}`,
  prev: 'Previous',
  next: 'Next',
  footerNote: 'Use the "Packages" page to create and edit credit packages — only that page checks a package is not loss-making before publishing.',
  modelEnabled: (model) => `${model} enabled`,
  modelDisabled: (model) => `${model} disabled`,
  toggleError: 'Failed to change model status',
  testModelError: 'Failed to test model',
  testResponded: (model, ms) => `${model} responded (${ms}ms)`,
  testFailed: (model, reason) => `${model} did not respond: ${reason}`,
  testUnknownReason: 'Unknown',
  saveOk: 'Tariff saved',
  saveError: 'Failed to save tariff',
  priceEmpty: (label) => `${label} price cannot be empty`,
  priceNotNumber: (label) => `${label} price must be a number`,
  priceNegative: (label) => `${label} price cannot be negative`,
  priceNotInteger: (label) => `${label} price must be a whole number (Toman)`,
  fieldInput: 'input',
  fieldOutput: 'output',
  currencyIrt: 'Toman',
  currencyIrr: 'Rial',
}

export const pricingStrings = dict(FA, EN)
