import { dict } from '@/lib/i18n'

const FA = {
  title: 'دعوت دوستان',
  subtitle: 'مبلغ پاداش معرف و معرفی‌شده، و آمار پرداخت‌ها.',
  loading: 'در حال بارگذاری…',
  noData: 'اطلاعاتی یافت نشد',
  loadError: 'خطا در دریافت تنظیمات دعوت',
  loadFailedTitle: 'دریافت تنظیمات دعوت ناموفق بود',
  retry: 'تلاش دوباره',
  serverError: (status: string) => `خطای سرور (${status})`,
  // Shown when GET/PUT /admin/referral/settings answers 404 -- the backend
  // route not existing yet (parallel work), not a real failure. See the
  // curl-verified `{"detail":"Not Found"}` note in the component.
  notBuiltTitle: 'این قابلیت هنوز فعال نشده است',
  notBuiltBody: 'سرویس تنظیمات دعوت هنوز روی بک‌اند نصب نشده. بعداً دوباره امتحان کنید.',
  referrerRewardLabel: 'پاداش معرف',
  referrerRewardHelp: 'مبلغی که به حساب کاربری که دعوت کرده واریز می‌شود.',
  inviteeRewardLabel: 'پاداش معرفی‌شده',
  inviteeRewardHelp: 'مبلغی که به حساب کاربر تازه‌واردی که دعوت شده واریز می‌شود.',
  capLabel: 'سقف تعداد پاداش به‌ازای هر معرف',
  capHelp: 'حداکثر تعداد دعوتی که برای یک کاربر پاداش‌دار حساب می‌شود؛ دعوت‌های بیشتر از این عدد، بدون پاداش می‌مانند.',
  unitToman: 'تومان',
  unitCount: 'دعوت',
  zeroNote: 'مقدار صفر یعنی این پاداش خاموش است — فقط ثبت‌نام و رابطهٔ دعوت‌کننده/دعوت‌شده ثبت می‌شود، پرداختی انجام نمی‌شود.',
  payoutNote: 'پاداش هرگز هنگام ثبت‌نام واریز نمی‌شود؛ فقط بعد از اولین پرداخت موفق کاربر دعوت‌شده.',
  statsTitle: 'آمار',
  statPending: 'در انتظار',
  statPaid: 'پرداخت‌شده',
  statCapped: 'به سقف رسیده',
  statTotalPaid: 'مجموع پرداختی',
  invalid: 'مقدار باید یک عدد صحیح نامنفی باشد.',
  invalidField: (label: string) => `${label}: مقدار باید یک عدد صحیح نامنفی باشد.`,
  save: 'ذخیره',
  cancel: 'انصراف',
  noChanges: 'تغییری برای ذخیره وجود ندارد',
  saved: 'تنظیمات دعوت ذخیره شد',
  saveErrorGeneric: 'ذخیره ناموفق بود',
}

const EN: typeof FA = {
  title: 'Referrals',
  subtitle: 'Referrer/invitee reward amounts and payout stats.',
  loading: 'Loading…',
  noData: 'No data found',
  loadError: 'Failed to load referral settings',
  loadFailedTitle: 'Failed to load referral settings',
  retry: 'Retry',
  serverError: (status) => `Server error (${status})`,
  notBuiltTitle: 'This feature is not live yet',
  notBuiltBody: 'The referral settings service is not deployed on the backend yet. Try again later.',
  referrerRewardLabel: 'Referrer reward',
  referrerRewardHelp: 'Amount credited to the user who sent the invite.',
  inviteeRewardLabel: 'Invitee reward',
  inviteeRewardHelp: 'Amount credited to the newly signed-up invited user.',
  capLabel: 'Reward cap per referrer',
  capHelp: 'Maximum number of referrals that count toward a reward for one user; referrals past this number are unrewarded.',
  unitToman: 'Toman',
  unitCount: 'referrals',
  zeroNote: 'A value of zero means this reward is off — signup and the referrer/invitee link are still recorded, but nothing is paid out.',
  payoutNote: "The reward is never paid at signup; only after the invited user's first successful payment.",
  statsTitle: 'Stats',
  statPending: 'Pending',
  statPaid: 'Paid',
  statCapped: 'Capped',
  statTotalPaid: 'Total paid',
  invalid: 'Value must be a non-negative whole number.',
  invalidField: (label) => `${label}: value must be a non-negative whole number.`,
  save: 'Save',
  cancel: 'Cancel',
  noChanges: 'No changes to save',
  saved: 'Referral settings saved',
  saveErrorGeneric: 'Save failed',
}

export const referralSettingsSectionStrings = dict(FA, EN)
