import { dict } from '@/lib/i18n'

const FA = {
  title: 'مرکز عملیات امنیتی (SOC)',
  subtitle: 'نظارت بر تهدیدات و عملیات ادمین',
  unbanSuccess: 'کاربر رفع مسدودیت شد',
  unbanError: 'خطا در رفع مسدودیت',
  threatLevelLabel: 'سطح تهدید',
  threatLabel: { low: 'پایین', medium: 'متوسط', high: 'بالا', critical: 'بحرانی' } as Record<string, string>,
  failedLogins24h: 'ورودهای ناموفق (۲۴ ساعت)',
  activeSessions: 'نشست‌های فعال',
  bannedUsersCount: 'کاربران مسدود شده',
  chartTitle: 'نمودار ورودهای ناموفق (۲۴ ساعت اخیر)',
  chartTooltip: (hour: string, count: string) => `${hour}: ${count} تلاش ناموفق`,
  bannedUsersTitle: 'کاربران مسدود شده',
  noBannedUsers: 'کاربر مسدود شده‌ای وجود ندارد',
  colId: 'شناسه',
  colUsername: 'نام کاربری',
  colEmail: 'ایمیل',
  colBannedAt: 'تاریخ مسدودیت',
  colActions: 'عملیات',
  unbanButton: 'رفع مسدودیت',
  auditLogTitle: 'لاگ عملیات ادمین',
  filterAll: 'همه',
  filterAdmin: 'عملیات ادمین',
  filterUsers: 'کاربران',
  filterModels: 'مدل‌ها',
  filterPricing: 'تعرفه‌ها',
  filterApiKey: 'کلید API',
  filterAuth: 'ورود و احراز هویت',
  colAction: 'عملیات',
  colTargetType: 'نوع هدف',
  colTargetId: 'شناسه هدف',
  colDetails: 'جزئیات',
  colTime: 'زمان',
  noAuditLogs: 'لاگ عملیاتی ثبت نشده',
  pageLabel: (page: string, count: string) => `صفحه ${page} از ${count}`,
  prev: 'قبلی',
  next: 'بعدی',
}

const EN: typeof FA = {
  title: 'Security Operations Center (SOC)',
  subtitle: 'Threat monitoring and admin operations',
  unbanSuccess: 'User unbanned',
  unbanError: 'Error unbanning user',
  threatLevelLabel: 'Threat level',
  threatLabel: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
  failedLogins24h: 'Failed logins (24h)',
  activeSessions: 'Active sessions',
  bannedUsersCount: 'Banned users',
  chartTitle: 'Failed login chart (last 24 hours)',
  chartTooltip: (hour, count) => `${hour}: ${count} failed attempts`,
  bannedUsersTitle: 'Banned users',
  noBannedUsers: 'No banned users',
  colId: 'ID',
  colUsername: 'Username',
  colEmail: 'Email',
  colBannedAt: 'Banned at',
  colActions: 'Actions',
  unbanButton: 'Unban',
  auditLogTitle: 'Admin audit log',
  filterAll: 'All',
  filterAdmin: 'Admin actions',
  filterUsers: 'Users',
  filterModels: 'Models',
  filterPricing: 'Pricing',
  filterApiKey: 'API key',
  filterAuth: 'Login & auth',
  colAction: 'Action',
  colTargetType: 'Target type',
  colTargetId: 'Target id',
  colDetails: 'Details',
  colTime: 'Time',
  noAuditLogs: 'No audit log entries',
  pageLabel: (page, count) => `Page ${page} of ${count}`,
  prev: 'Previous',
  next: 'Next',
}

export const securitySectionStrings = dict(FA, EN)
