import { dict } from '@/lib/i18n'

const FA = {
  creditLabel: 'شارژ (افزایش)',
  debitLabel: 'کسر (کاهش)',
  sectionTitle: 'شارژ / کسر کیف پول',
  amountLabel: 'مبلغ (تومان)',
  amountPlaceholder: 'مثلاً 50000',
  txTypeLabel: 'نوع تراکنش',
  reasonLabel: 'دلیل (الزامی)',
  reasonPlaceholder: 'مثلاً جبران خطای فنی',
  submitRequest: 'ثبت درخواست',
  panelSectionTitle: 'پنل کاربر',
  consumerLabel: 'مصرف‌کننده',
  developerLabel: 'توسعه‌دهنده',
  currentStatus: (label: string) => `وضعیت فعلی: ${label}`,
  amountInvalid: 'مبلغ باید عدد صحیح و بزرگ‌تر از صفر باشد',
  reasonRequired: 'ذکر دلیل الزامی است',
  creditSuccess: 'کیف پول شارژ شد',
  debitSuccess: 'از کیف پول کسر شد',
  walletError: 'خطا در ثبت تراکنش کیف پول',
  toDeveloperSuccess: 'کاربر به پنل توسعه‌دهنده منتقل شد',
  toConsumerSuccess: 'کاربر به پنل مصرف‌کننده منتقل شد',
  panelError: 'خطا در جابه‌جایی پنل',
  confirmTitle: 'تأیید تراکنش کیف پول',
  typeLabel: 'نوع:',
  confirmAmountLabel: 'مبلغ:',
  currentBalanceLabel: 'موجودی فعلی:',
  confirmReasonLabel: 'دلیل:',
  confirmSubmit: 'تأیید و اعمال',
  submitting: 'در حال ثبت...',
  cancel: 'انصراف',
}

const EN: typeof FA = {
  creditLabel: 'Credit (increase)',
  debitLabel: 'Debit (decrease)',
  sectionTitle: 'Credit / debit wallet',
  amountLabel: 'Amount (Toman)',
  amountPlaceholder: 'e.g. 50000',
  txTypeLabel: 'Transaction type',
  reasonLabel: 'Reason (required)',
  reasonPlaceholder: 'e.g. technical error compensation',
  submitRequest: 'Submit',
  panelSectionTitle: 'User panel',
  consumerLabel: 'Consumer',
  developerLabel: 'Developer',
  currentStatus: (label) => `Current: ${label}`,
  amountInvalid: 'The amount must be a positive integer',
  reasonRequired: 'A reason is required',
  creditSuccess: 'Wallet credited',
  debitSuccess: 'Wallet debited',
  walletError: 'Error recording the wallet transaction',
  toDeveloperSuccess: 'User moved to the developer panel',
  toConsumerSuccess: 'User moved to the consumer panel',
  panelError: 'Error switching panel',
  confirmTitle: 'Confirm wallet transaction',
  typeLabel: 'Type:',
  confirmAmountLabel: 'Amount:',
  currentBalanceLabel: 'Current balance:',
  confirmReasonLabel: 'Reason:',
  confirmSubmit: 'Confirm and apply',
  submitting: 'Submitting...',
  cancel: 'Cancel',
}

export const userWalletOpsStrings = dict(FA, EN)
