import { dict } from '@/lib/adminI18n'

const FA = {
  tabOverview: 'نمای کلی',
  tabWallet: 'کیف پول',
  tabPayments: 'پرداخت‌ها',
  tabUsage: 'مصرف',
  tabConversations: 'گفتگوها',
  tabActions: 'اقدامات',
  userFallback: (uid: string) => `کاربر #${uid}`,
  idPrefix: (uid: string) => `شناسه ${uid}`,
  close: 'بستن',
  fetchError: 'خطا در دریافت اطلاعات کاربر',
  retry: 'تلاش دوباره',
  statusBanned: 'مسدود',
  statusActive: 'فعال',
  ledgerFetchError: 'خطا در دریافت تراکنش‌ها',
  paymentsFetchError: 'خطا در دریافت پرداخت‌ها',
  usageFetchError: 'خطا در دریافت مصرف',
  conversationsFetchError: 'خطا در دریافت گفتگوها',
  dailyLimitInvalid: 'سقف روزانه باید عدد صحیح و غیرمنفی باشد',
  noChangesToSave: 'تغییری برای ذخیره وجود ندارد',
  saveSuccess: 'اطلاعات کاربر بروزرسانی شد',
  saveError: 'خطا در ذخیره اطلاعات کاربر',
  statWalletBalance: 'موجودی کیف پول',
  statReserved: 'رزرو شده',
  statConversations: 'گفتگوها',
  statTotalCost: 'هزینه کل',
  statVerifiedPayments: 'پرداخت‌های تایید شده',
  statTotalTokens: 'توکن مصرفی',
  fieldName: 'نام',
  fieldEmail: 'ایمیل',
  fieldPhone: 'تلفن',
  fieldTelegram: 'تلگرام',
  fieldDailyLimit: 'سقف روزانه',
  fieldUsedToday: 'مصرف امروز',
  fieldJoinedAt: 'تاریخ عضویت',
  fieldPanel: 'پنل',
  panelDeveloper: 'توسعه‌دهنده',
  panelConsumer: 'مصرف‌کننده',
  aiPersonalityLabel: 'شخصیت هوش مصنوعی: ',
  walletHistoryTitle: 'تاریخچه تراکنش‌های کیف پول',
  banSectionTitle: 'مسدودسازی',
  unbanUser: 'رفع مسدودیت',
  banUser: 'مسدود کردن کاربر',
  currentStatus: (status: string) => `وضعیت فعلی: ${status}`,
  editInfoTitle: 'ویرایش اطلاعات کاربر',
  emailField: 'ایمیل',
  phoneField: 'تلفن',
  dailyLimitField: 'سقف روزانه (تعداد درخواست)',
  walletEditNote: 'ویرایش مستقیم موجودی کیف پول از این فرم ممکن نیست — از تب «کیف پول» استفاده کنید.',
  savingLabel: 'در حال ذخیره...',
  saveChanges: 'ذخیره تغییرات',
  panelMoveTitle: 'جابه‌جایی پنل',
  panelMoveNote: 'انتقال بین پنل مصرف‌کننده و توسعه‌دهنده از تب «کیف پول» انجام می‌شود.',
}

const EN: typeof FA = {
  tabOverview: 'Overview',
  tabWallet: 'Wallet',
  tabPayments: 'Payments',
  tabUsage: 'Usage',
  tabConversations: 'Conversations',
  tabActions: 'Actions',
  userFallback: (uid) => `User #${uid}`,
  idPrefix: (uid) => `ID ${uid}`,
  close: 'Close',
  fetchError: 'Error loading user data',
  retry: 'Retry',
  statusBanned: 'Banned',
  statusActive: 'Active',
  ledgerFetchError: 'Error loading transactions',
  paymentsFetchError: 'Error loading payments',
  usageFetchError: 'Error loading usage',
  conversationsFetchError: 'Error loading conversations',
  dailyLimitInvalid: 'The daily limit must be a non-negative integer',
  noChangesToSave: 'No changes to save',
  saveSuccess: 'User info updated',
  saveError: 'Error saving user info',
  statWalletBalance: 'Wallet balance',
  statReserved: 'Reserved',
  statConversations: 'Conversations',
  statTotalCost: 'Total cost',
  statVerifiedPayments: 'Verified payments',
  statTotalTokens: 'Tokens used',
  fieldName: 'Name',
  fieldEmail: 'Email',
  fieldPhone: 'Phone',
  fieldTelegram: 'Telegram',
  fieldDailyLimit: 'Daily limit',
  fieldUsedToday: 'Used today',
  fieldJoinedAt: 'Joined',
  fieldPanel: 'Panel',
  panelDeveloper: 'Developer',
  panelConsumer: 'Consumer',
  aiPersonalityLabel: 'AI personality: ',
  walletHistoryTitle: 'Wallet transaction history',
  banSectionTitle: 'Ban',
  unbanUser: 'Unban',
  banUser: 'Ban user',
  currentStatus: (status) => `Current status: ${status}`,
  editInfoTitle: 'Edit user info',
  emailField: 'Email',
  phoneField: 'Phone',
  dailyLimitField: 'Daily limit (request count)',
  walletEditNote: 'The wallet balance cannot be edited directly from this form — use the "Wallet" tab.',
  savingLabel: 'Saving...',
  saveChanges: 'Save changes',
  panelMoveTitle: 'Panel switch',
  panelMoveNote: 'Moving between the consumer and developer panel is done from the "Wallet" tab.',
}

export const userDetailDrawerStrings = dict(FA, EN)
